Feature/dd20 format validation 2
energinet-singularity/conductor-data-provider pull request #25
Opened 2022-06-16 10:46 UTC by cjjohansen

**Adds a hash value check of the dd20 excell sheets to detect any changes in the file format**

Category:

- [x ] New Feature
- [ ] Bugfix
- [ ] Documentation update

Checklist:

- [x ] I have bumped all relevant version numbers
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ ???] I have documented my changes if this is needed
- [??? ] I have described my changes in the "description of your changes" field
- [ ] I have tested this change on a running cluster 
- [x] I have created/corrected automated tests related to the changes, if possible/necessary
- [x] I have checked that new and existing unit tests pass locally with my changes
- [ ] I have squashed commits if necessary

2022-06-16 15:41 UTC, swedchef requested changes
Generally well-written and good level - Almost looks like you tried this before! ;)

I found some issues though - most important, you are not calculating the hash for the rows you claim in the docstring - this will have to be fixed. Furthermore i would like to request fewer empty lines, and marked some formatting items as well.

Have a look at my suggestions - peace out!

2022-06-16 15:41 UTC, swedchef commented on app/helpers/dd20_format_validation.py
> +
```suggestion
    """Calculate hash value for first 3 rows in data frame

    Convert header-rows to a string and calculate a hash
    from them (they are considered static header rows).
    Used to detect if the file format has changed.

    Parameters
    ----------
    data_frame: pd.DataFrame
        dd20 data frame

    Returns
    -------
    str
        Calculated hash value of header rows
    """
```
I think the current description is a bit misleading compared to what it actually does.

2022-06-16 15:41 UTC, swedchef commented on app/helpers/dd20_format_validation.py
> +    DD20_HEADER_END_INDEX = 2
```suggestion
    DD20_HEADER_BEGIN_INDEX = 0
    DD20_HEADER_END_INDEX = 3
```
The row numbering is zero-based, so first row will be row zero. Furthermore, the second integer will be the first row that is NOT included. So by using 1 and 2 you only get the second row of the pandas dataframe. If you want the first three rows you will need to use 0 and 3 as input.

2022-06-16 15:41 UTC, swedchef commented on app/helpers/dd20_format_validation.py
> +    rows_encoded = rows_as_string.encode()
```suggestion
    rows_encoded = rows.to_string().encode()
```
I get this about being explicit, especially in python for readability, but i would personally prefer this was joined. Up to you.

2022-06-16 15:41 UTC, swedchef commented on app/helpers/dd20_format_validation.py
> +
```suggestion
class DD20FormatError(Exception): pass

```
As you don't modify the super-class, i don't understand why you would want to do this. Why not just call a standard exception of some sort? KeyError, ValueError - something.

And remember the last line of the file has to be empty - here it contains whitespace! :)

2022-06-16 15:41 UTC, swedchef commented on app/helpers/parse_dd20.py
> +    station_data_valid_format_hash_value: str = "91006da47706518d76724105a97dfb61"
```suggestion
    line_data_valid_hash: str = "eb087129d0c2413ee9768957c2c847ae", 
    station_data_valid_hash: str = "91006da47706518d76724105a97dfb61" 
```
Just an opinion, but i think these variable names are equally specific ("value" is generic - everything is a value?) and format does not much add much in my opinion. Go with your preferred style.

2022-06-16 15:41 UTC, swedchef commented on app/helpers/parse_dd20.py
> +        hash value of the header rows in the dd20 line sheet, used to detect a change in file format.
```suggestion
        Hash value of the header rows in the dd20 line sheet,
        used to detect a change in file format.
```

2022-06-16 15:41 UTC, swedchef commented on app/helpers/parse_dd20.py
> +        hash value of the header rows in the dd20 station sheet, used to detect a change in file format.
```suggestion
        Hash value of the header rows in the dd20 station sheet,
        used to detect a change in file format.
```

2022-06-17 06:45 UTC, cjjohansen commented on .vscode/settings.json
> +}
It could be shared between the team, so we have the same setup.
Do you still think i should remove it ?

2022-06-17 06:47 UTC, cjjohansen commented on app/helpers/dd20_format_validation.py
> +
To be specific. Its allways good practice to make your own Error Classes as a way to communicate the type of error.

2022-06-17 06:49 UTC, cjjohansen commented on app/helpers/parse_dd20.py
> +    station_data_valid_format_hash_value: str = "91006da47706518d76724105a97dfb61"
valid suggestion. I Take it :-)

2022-06-17 06:50 UTC, cjjohansen commented on tests/test_combine_data.py
> +print("adding to sys.path...")
aggree

2022-06-17 06:53 UTC, cjjohansen commented on tests/test_dd20_format_validation.py
> +    )
good question :-)

2022-06-17 06:53 UTC, cjjohansen commented on tests/test_dd20_format_validation.py
> +    )
maybe its  a reserved keyword

2022-06-17 06:57 UTC, cjjohansen commented on app/helpers/dd20_format_validation.py
> +
it should be row 1,2 not including the first row. So yes the description should be updated

2022-06-17 06:58 UTC, cjjohansen commented on app/helpers/dd20_format_validation.py
> +    DD20_HEADER_END_INDEX = 2
will keep numbers but change description

2022-06-17 07:37 UTC, cjjohansen commented on .vscode/settings.json
> +}
removed

2022-06-17 07:38 UTC, cjjohansen commented on app/helpers/dd20_format_validation.py
> +    DD20_HEADER_END_INDEX = 2
changed to 1:3 to get rows 1,2

2022-06-17 11:11 UTC, swedchef commented on app/helpers/dd20_format_validation.py
> +    DD20_HEADER_END_INDEX = 2
Well - it is still 1 and 2 in the code - i agree, if you are looking for row 1 and 2, END_INDEX should be 3.

2022-06-17 11:16 UTC, swedchef commented on app/helpers/dd20_format_validation.py
> +    DD20_HEADER_END_INDEX = 2
You are adding a "magic" one in line 44 - i don't like that. I kind of understand why - but still - python works like this and it is more confusing to me at least.

2022-06-17 11:24 UTC, swedchef requested changes
Just a few more - oh and could you please have a look at your description of the pull-request. The way you marked the check-boxes seems to have made the markdown throw up! :(

2022-06-17 11:24 UTC, swedchef commented on app/helpers/parse_dd20.py
> +        used to detect a change in file format.
```suggestion
    line_data_valid_hash : str, Default = "d1408314abb87bfb0c0b1e7665338575" 
        Hash value of the header rows in the dd20 line sheet,
        used to detect a change in file format.
    station_data_valid_hash : str, Default =  "3623a788db1ed713d67511241737cf05"     
        Hash value of the header rows in the dd20 station sheet,
        used to detect a change in file format.
```

2022-06-17 11:24 UTC, swedchef commented on tests/test_dd20_format_validation.py
> +from  helpers.parse_dd20 import parse_dd20_excelsheets_to_dataframe
```suggestion
import os
from sys import path
# Ugly hack to allow absolute import from the root folder
# whatever its name is. Please forgive the heresy.
path.append(os.path.join(os.path.split(os.path.split(__file__)[0])[0], "app"))

import pandas as pd
import pytest
import helpers.dd20_format_validation as validators
from helpers.parse_dd20 import parse_dd20_excelsheets_to_dataframe
```

2022-06-17 11:33 UTC, cjjohansen commented on app/helpers/dd20_format_validation.py
> +    DD20_HEADER_END_INDEX = 2
Aggree not so understandable
alternative is to just use  [DD20_HEADER_BEGIN_INDEX,DD20_HEADER_END_INDEX, :]
: -> ,

2022-06-17 11:41 UTC, cjjohansen commented on app/helpers/dd20_format_validation.py
> +    DD20_HEADER_END_INDEX = 2
changed code to avoid +1

2022-06-17 11:59 UTC, swedchef submitted a review, later dismissed
Nice fix with the row selection, i didn't think of that - if you REALLY want it nice, i would argue it would look better with  the following:
````python
DD20_HEADER_ROWS = [1,2]
rows = data_frame.iloc[DD20_HEADER_ROWS, :]
````

If you want to quick-fix it, i can re-approve as well 🥇

2022-06-17 12:00 UTC, swedchef commented
You will have to rebase anyways as some commits are not signed!

2022-06-20 12:51 UTC, swedchef approved these changes
Best thing i ever made without making it

2022-06-21 06:15 UTC, merged