moves all settings into configuration class and use pydantic to easil…
energinet-singularity/conductor-data-provider pull request #28
Opened 2022-06-21 11:20 UTC by cjjohansen

…iy load from env vars

**Description of your changes**

Category:

- [ ] New Feature
- [ ] Bugfix
- [ ] Documentation update

Checklist:

- [ ] I have bumped all relevant version numbers
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have documented my changes if this is needed
- [ ] I have described my changes in the "description of your changes" field
- [ ] I have tested this change on a running cluster 
- [ ] I have created/corrected automated tests related to the changes, if possible/necessary
- [ ] I have checked that new and existing unit tests pass locally with my changes
- [ ] I have squashed commits if necessary

2022-06-22 07:00 UTC, xandvenerginet requested changes

2022-06-22 07:00 UTC, xandvenerginet commented on .env
> +DD20_STATION_DATA_VALID_HASH="3623a788db1ed713d67511241737cf05"
Does the 'DD20' prefix add any value in this context? Isn't it a DD20 specific service?

2022-06-22 07:00 UTC, xandvenerginet commented on app/main.py
> +            f"'USE_MOCK_DATA' env. variable is '{settings.use_mock_data}',"
Ins't this checked by pydantic? In any case seems like the responsiblity of the parsing logic.

2022-06-22 07:00 UTC, xandvenerginet commented on app/main.py
> +    if not settings.use_mock_data:
Could this check on mock data flag be moved to the config class? Maybe not the best place but probably better than here.

Alternatively (and much better, imho), do not put this responsibility on the code, but leave it as a configuration. Instead of using a mock data flag, simply change the configuration's data path to point to mock data. This remove the responsibility from the code.

2022-06-22 07:08 UTC, cjjohansen commented on .env
> +DD20_STATION_DATA_VALID_HASH="3623a788db1ed713d67511241737cf05"
Just a precaution to avoid any name clashes with other environment variables

2022-06-22 07:14 UTC, cjjohansen commented on app/main.py
> +    if not settings.use_mock_data:
Yes good idea. I aggree. Would need to look into how to do that with pydantic. Since now its no longer a qustion of just parsing variables. Also the task grows :-) There are still more that could be improved :-)

2022-06-22 07:16 UTC, cjjohansen commented on app/main.py
> +            f"'USE_MOCK_DATA' env. variable is '{settings.use_mock_data}',"
it is yes :-)

2022-06-22 07:17 UTC, cjjohansen commented on .env
> +DD20_STATION_DATA_VALID_HASH="3623a788db1ed713d67511241737cf05"
Specially since we yet dont use vritual environment and developeprs work with many projects on the same dev machine. But a valid point.

2022-06-22 11:00 UTC, cjjohansen commented on app/main.py
> +            f"'USE_MOCK_DATA' env. variable is '{settings.use_mock_data}',"
removed

2022-06-22 11:09 UTC, xandvenerginet commented on app/helpers/dd20_configuration.py
> +    use_mock_data: bool = False
is this still needed?

2022-06-22 11:13 UTC, xandvenerginet commented on app/main.py
> +    if not settings.use_mock_data:
I  am advocating that we skip the use_mock_data check completely as well as the mock_data property,and instead have one data property that can be configured to either point to real or mock data. The application doesn't need to know runtime.

2022-06-23 06:38 UTC, xandvenerginet approved these changes

2022-06-23 07:44 UTC, swedchef requested changes
I am uncertain, but i think this will actually break the current functionality. Where do we load variables from the environment? As i can see we only write them to the environment, and i don't even understand/know why we would want to do that.

I think both pydantic and dotenv are over the top for the current implementation and only adds unwanted complexity - i really don't see what they give us as we will be using the compiled containers and will be setting env. variables from the outside, not through a file inside the container. I get we will receive input validation, but given the low complexity of this application/service and that we are in complete control of the environment it will be running in, i think that is a bit over the top.

2022-06-23 07:44 UTC, swedchef commented on app/main.py
> +from dotenv import load_dotenv
Why are we using this package and the .env file at all? Why not specify the settings in the config file itself as we have done before (forecast parser if i recall correctly)? In general we will be deploying using the compiled containers, so it will be of little use to us. We set out settings through environment variables, not files in the container itself.

2022-06-23 07:44 UTC, swedchef commented on app/helpers/dd20_configuration.py
> +        Important: Order of fields are important
Why is the order important?

2022-06-23 07:44 UTC, swedchef commented on app/helpers/dd20_configuration.py
> +from pydantic import BaseSettings, root_validator, Field
Why are we using pydantic? It seems like a lot of work and hassle for some type validation. I don't see that we gain that much from it - other than added complexity. If it was a more advanced application/service, i could see the usecase though.

2022-06-23 07:44 UTC, swedchef commented on chart/Chart.yaml
> +version: 1.1.1
I I would argue that this is more than a patch - at least a minor.

2022-06-23 07:44 UTC, swedchef commented on chart/values.yaml
> +  tag: "1.1.1"
I would argue that this is more than a patch - at least a minor.

2022-06-23 07:44 UTC, swedchef commented on tests/empty.env
> +# Should be empty
What is this and why is it here?

2022-06-23 07:44 UTC, swedchef commented on tests/test_load_configuration.py
> +
No blank line

2022-06-23 08:02 UTC, cjjohansen commented
> I am uncertain, but i think this will actually break the current functionality. Where do we load variables from the environment? As i can see we only write them to the environment, and i don't even understand/know why we would want to do that.
> 
> I think both pydantic and dotenv are over the top for the current implementation and only adds unwanted complexity - i really don't see what they give us as we will be using the compiled containers and will be setting env. variables from the outside, not through a file inside the container. I get we will receive input validation, but given the low complexity of this application/service and that we are in complete control of the environment it will be running in, i think that is a bit over the top.

The pydantic baseSettings class reads from the env variables. We only write to them in tests to make a deterministic test.

2022-06-23 08:20 UTC, cjjohansen commented on app/helpers/dd20_configuration.py
> +        env_file = ".env"
We set default values in the setting class. The values in enviornment vars are the real values. Right ?!

pydantic can load both from .env file and or from real environment variables. The real env variables win accordingto pydantic documentation

"Even when using a dotenv file, pydantic will still read environment variables as well as the dotenv file, environment variables will always take priority over values loaded from a dotenv file."

https://pydantic-docs.helpmanual.io/usage/settings/

That is part of the pydantic package.

2022-06-23 08:24 UTC, cjjohansen commented on app/main.py
> +from dotenv import load_dotenv
Its a convenient way to control settings in tests and directly from code.
In A deployment scenario you also want to be able to specify what the environment variables should be.
I Recommend reading the two blog posts posted in teams.


[(https://tech.preferred.jp/en/blog/working-with-configuration-in-python/)]

[(https://towardsdev.com/store-configuration-with-pydantic-basesettings-for-your-python-project-4994967e520)]

2022-06-23 08:32 UTC, cjjohansen commented on chart/Chart.yaml
> +version: 1.1.1
OK. The functionality has not changed. But yes saying its just a patch may sound as to little

2022-06-23 09:08 UTC, swedchef commented on app/helpers/dd20_configuration.py
> +from pydantic import BaseSettings, root_validator, Field
We already had some code doing a simple version of the same in our last delivery, but i see how this is smarter and better. Agree on using pydantic.

2022-06-23 09:12 UTC, swedchef commented on chart/Chart.yaml
> +version: 1.1.1
The reason i think we are in minor (at least) is the change of environment variable names - so this container will not be able to run with an "old" config in case it uses environment variables. If we were to skip the DD20 prefix (as i argue we should), i would say it would be grey area between patch and minor as it does not change functionality towards the "user", but it does change a lot in the "backend".

2022-06-23 11:05 UTC, cjjohansen commented on chart/values.yaml
> +  tag: "1.1.1"
will bump minor version then

2022-06-23 11:05 UTC, cjjohansen commented on tests/empty.env
> +# Should be empty
I will explain in more details in the comment then

2022-06-23 11:40 UTC, cjjohansen commented on tests/test_load_configuration.py
> +
fixed

2022-06-23 12:04 UTC, cjjohansen commented on app/main.py
> +from dotenv import load_dotenv
We can reomve th call and the import now since pydantic takes care of it. But pydantic still needs the dotenv package.

removed import 
and call

2022-06-23 12:07 UTC, cjjohansen commented on README.md
> +|DD20_USE_MOCK_DATA|(not set)|Set to 'TRUE' to enable creating mock forecast files|
I would keep the prefix because og the name clashing argument.
Also i dont think its that misleading. 
Could we use a better prefix name?
What do you think

2022-06-23 14:39 UTC, swedchef commented on README.md
> +|MAPPING_FILEPATH|/input/Limits_other.xlsx|Filepath for "DD20 name to SCADA AC-line name mapping" excel-file.|
```suggestion
|DD20_MAPPING_FILEPATH|/input/Limits_other.xlsx|Filepath for "DD20 name to SCADA AC-line name mapping" excel-file.|
```
This should not change

2022-06-24 11:46 UTC, swedchef requested changes
We are getting closer. I really like the pydantic inclusion.

2022-06-24 11:46 UTC, swedchef commented on tests/empty.env
> +# an empty .env file
We don't need this file - when we are working/testing locally (during development) we should use the app/.env file and when we are staging tests (pytest etc.), we should instantiate DD20Settings with the configuration we want as it skips a step and makes it easy to see what configuration we are using.
````python
test_config = {
    debug = True,
    use_mock_data = False,
    station_format_hash = "1234567890",
}
settings = DD20Settings(test_config)
````

2022-06-24 11:46 UTC, swedchef commented on README.md
>  |USE_MOCK_DATA|(not set)|Set to 'TRUE' to enable creating mock forecast files|
```suggestion
|USE_MOCK_DATA|False|Set to 'TRUE' to enable creating mock forecast files|
```
Given we are using pydantic this is actually default "False" now.

2022-06-24 11:46 UTC, swedchef commented on README.md
>  |DEBUG|(not set)|Set to 'TRUE' to enable very verbose debugging log|
```suggestion
|DEBUG|False|Set to 'TRUE' to enable very verbose debugging log|
```
Given we are using pydantic this is actually default "False" now.

2022-06-24 11:46 UTC, swedchef commented on README.md
> +|MOCK_MRID_MAPPING_FILEPATH|tests/valid-testdata/seg_line_mrid_PROD.csv|Filepath for "AC-line name to AC-linesegment MRID mapping" csv-file from SCADA system.|
Just an opinion: These are not really settings, but more included as an option to have a work-around in case something goes wrong. I think it would be fair to leave them out of the README
```suggestion
```
For forecast-parser i disclaimed by using the following string at the end of the list:
More environment variables have been exposed, but will rarely be used. They can be found in the values.yaml file in the chart directory.

2022-06-24 11:46 UTC, swedchef commented on README.md
> +|MOCK_MRID_MAPPING_FILEPATH|tests/valid-testdata/seg_line_mrid_PROD.csv|Filepath for "AC-line name to AC-linesegment MRID mapping" csv-file from SCADA system.|
Oh - and in case you decide to leave them in - remember to change "MAPPING_FILEPATH" to "DD20_MAPPING_FILEPATH" as this is the original parameter name and describes it better.

2022-06-24 11:46 UTC, swedchef commented on app/main.py
> +            print(f'{k}={v}')
I guess this is a left-over from a test you did?
```suggestion
```
It should be removed as print is not good - and i see it as bad practice to print all environment variables. We could add a log.debug() for all items in the settings object, but i am guessing that the pydantic module probably debug writes what the settings it has by default - or at least if they change from their initial setting.

2022-06-24 11:46 UTC, swedchef commented on app/main.py
> +        raise ValueError("Error while reading application settings.")
````suggestion
    except Exception as e:
        log.error("Error while reading application settings.")
        log.exception(e)
        raise e
````
I think we need to re-raise in stead of continuing and then log well before quitting

2022-06-24 11:46 UTC, swedchef commented on app/configuration.py
> +    line_data_valid_hash: str
These need to be filled out or the container will never start up - or you will have to inject the hash'es, but as they should ideally never change, why would we not default the values? This makes it harder to start the container as anyone wanting to start it will have to provide values - that never change.

If we don't want to use default values, i would argue these values should be changed from variables/parameter to constants that are hard-coded into the code. They really shouldn't change.

2022-06-24 11:46 UTC, swedchef commented on app/configuration.py
> +        case_sensitive = False
````suggestion
````
AFAIK these are the default values for the settings and don't need to be explicitly set.

2022-06-24 11:46 UTC, swedchef commented on app/configuration.py
> +        env_file = "./app/.env"
```suggestion
        env_file = "app/.env"
```
"./" just references the current folder so should not be necessary.
I will say though - i am uncertain how pydantic reads the path, and if it does so like standard python (i guess it does) it will start in cwd, which could make the relative path you have provided non-functional. So perhaps:
```suggestion
        import os # Move me to the top!
        env_file = os.path.join(os.path.split(os.path.abspath(__file__))[0], ".env")
```

2022-06-24 11:46 UTC, swedchef commented on chart/values.yaml
> +  #MAPPING_FILEPATH: "/this/place/file.xlsx"
```suggestion
  #DD20_MAPPING_FILEPATH: "/this/place/file.xlsx"
```

2022-06-24 11:46 UTC, swedchef commented on chart/values.yaml
> +  #TODO: How do we parametrice variables? We will need different values for different deployment environments
```suggestion
```

2022-06-24 12:01 UTC, cjjohansen commented on README.md
> +|MAPPING_FILEPATH|/input/Limits_other.xlsx|Filepath for "DD20 name to SCADA AC-line name mapping" excel-file.|
Fixed

2022-06-24 12:06 UTC, cjjohansen commented on tests/empty.env
> +# an empty .env file
excellent point. Thx for pointing that out. We can use that approach

2022-06-27 07:14 UTC, cjjohansen commented on app/configuration.py
> +    line_data_valid_hash: str
Its better to have one way to do things. And that one way should make it possible to set configuration from outside the code. If we keep things the way its is we make a special case.  That would be my counter argument.
Normally it should be possible to go change such configurations from a UI or command line rather than have to get a developer find the place in code where it should be changed, push to git, redeploy etc.

2022-06-27 07:16 UTC, cjjohansen commented on app/configuration.py
> +    line_data_valid_hash: str
@stigsberg This is an important point, The original idea of the task was NOT to hard code the hash values in code. Now he counter argument seems to be that we cannot start teh container if we don't hard code it. Im configdent its the wrong way to do things, but the questio is what we do now.

2022-06-27 07:18 UTC, cjjohansen commented on app/configuration.py
> +        case_sensitive = False
Valid point. The thing is its convenient as an example. And for local testing you might whant to change the prefix. I dont hink it hurts if its there.

2022-06-27 07:24 UTC, cjjohansen commented on chart/values.yaml
> +  #TODO: How do we parametrice variables? We will need different values for different deployment environments
Why will you remove it ?

2022-06-27 07:41 UTC, cjjohansen commented on app/main.py
> +        raise ValueError("Error while reading application settings.")
Weird I cannot se that there are two raise after each other

2022-06-27 07:46 UTC, cjjohansen commented on app/main.py
> +        raise ValueError("Error while reading application settings.")
Added log statement before raise

2022-06-27 07:50 UTC, cjjohansen commented on README.md
> +|MOCK_MRID_MAPPING_FILEPATH|tests/valid-testdata/seg_line_mrid_PROD.csv|Filepath for "AC-line name to AC-linesegment MRID mapping" csv-file from SCADA system.|
I don't understand how they are not settings. Well yes if you assume they will never ever change. But often you want to change them any way because of the convenience it brings in various test scenarios

2022-06-27 07:50 UTC, cjjohansen commented on README.md
> +|MOCK_MRID_MAPPING_FILEPATH|tests/valid-testdata/seg_line_mrid_PROD.csv|Filepath for "AC-line name to AC-linesegment MRID mapping" csv-file from SCADA system.|
Will not remove.

2022-06-27 09:36 UTC, cjjohansen commented on app/configuration.py
> +    line_data_valid_hash: str
OK Since we don't yet have a formalized CI/CD pipline. Lets revert to the currently aggreed way of doing things. Which is hardcoding the default value / constant in code.
At some time we need to revisit and mature this.

2022-06-27 09:47 UTC, cjjohansen commented on app/configuration.py
> +    line_data_valid_hash: str
reverted

2022-06-27 09:48 UTC, cjjohansen commented on chart/values.yaml
> +  #TODO: How do we parametrice variables? We will need different values for different deployment environments
The statement is still valid. Will not remove :-)

2022-06-27 10:28 UTC, stigsberg requested changes
I have read the changes in this PR.
As agreed on, I have not done anything to evaluate the decision on pydantic because of the time constraint. I have some issues that needs to addressed to make the services run in production. Maybe a manual test of the running container/helm should be done since we don't have a real test environment at the present time.

2022-06-27 10:28 UTC, stigsberg commented on tests/test_load_configuration.py
> +    expected_line_data_hash = "A"
In all of these test cases you are using a stack of the same "expected values" and of course you change some of them to make an invalid input which maybe it should have been the os.environment that changed. But it is incredibly heavy to read almost the same parameters four times and see the difference which is minor and it is also the reason the test failed at one point because of a type error which was not meant to be there.
Since you choose to lower case all the vars. (so they are not constants) I will suggest you move them all out of the functions and just overwrite the parameters you are trying to test. It will greatly reduce the number of repeated lines and make it VERY clear what parameter you are testing in each function at a glance. As an added bonus if the default values change you are not going to correct the same value in more than one place.
And I see the point that @swedchef made about testing the module itself it is valid but the test are written and does not hurt so lets just keep them but please do something about the overview of what you are testing. :)

2022-06-27 10:29 UTC, stigsberg commented on chart/values.yaml
> +  #TODO: How do we parametrice variables? We will need different values for different deployment environments
Like issues and alike lets pull things not fixed out of the running code instead of hiding within the code base. :)

2022-06-27 10:40 UTC, cjjohansen commented on chart/values.yaml
> +  #TODO: How do we parametrice variables? We will need different values for different deployment environments
OK I will delete it then nad create a story/ticket

2022-06-27 10:56 UTC, cjjohansen commented on app/configuration.py
> +        case_sensitive = False
There is a rule saying when reading data you should be forgiving, when writing data you should be strict.
I think default value in pydantic is to have it to false. IF we change it to true, then we have to aling code casing with env var casing. Normally env vars are in UPPER case where as python code is lower case. As I se it we just create problems and more work chaning to being case sensitive. If we look at  [pydantic documentation](https://pydantic-docs.helpmanual.io/usage/settings/ ) they have class fields in lower case but settings/env vars in upper case. So I recommend not chaning it.

2022-06-27 12:04 UTC, cjjohansen commented on tests/test_load_configuration.py
> +    expected_line_data_hash = "A"
Aggree that I can remove duplicated initialization of fields. Just felt it was on the verge of gold plating in this particular case. Normally I would also point it out myself. So I aggree. I will take the time and remove duplication.

2022-06-28 06:18 UTC, stigsberg submitted a review, later dismissed
LGTM

2022-06-28 07:09 UTC, stigsberg approved these changes
Nice signing! :)

2022-06-28 11:05 UTC, stigsberg approved these changes
Now signing works!

2022-06-28 11:06 UTC, merged