Feature/dd20 format change
energinet-singularity/conductor-data-provider pull request #9
Opened 2022-05-17 05:48 UTC by CodeWitten

**Description of your changes**

Category:

- [ ] New Feature
- [ ] Bugfix
- [ ] Documentation update

Checklist:

- [ ] I have bumped all relevant version numbers
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have documented my changes if this is needed
- [ ] I have described my changes in the "description of your changes" field
- [ ] I have tested this change on a running cluster 
- [ ] I have created/corrected automated tests related to the changes, if possible/necessary
- [ ] I have checked that new and existing unit tests pass locally with my changes
- [ ] I have squashed commits if necessary

2022-05-18 09:27 UTC, stigsberg requested changes
I've tested spinning the container up using mock data and SQL to it.
It works. :)

2022-05-18 09:27 UTC, stigsberg commented on README.md
> +|DBNAME|CONDUCTOR_DATA|Name of database exposed via REST API|
Consider renaming the variables to make it clear that they refer to the API setup.

2022-05-18 09:27 UTC, stigsberg commented on README.md
```suggestion
####SQL command
When the container is running in your local environment you can use the following bash command to query data from it. The example below assumes you are using Mock data with default settings, please change "localhost" with the IP that your API is running on.
````bash
curl -d '{"sql-query": "SELECT * FROM CONDUCTOR_DATA;"}' -H 'Content-Type: application/json' -X POST http://localhost:5000/
````
```

2022-05-18 14:32 UTC, swedchef requested changes
Very nice - good style and structure.

Regarding pytest - it would be nice to check bad input results in errors - use this style to check for raised errors with bad input:
with pytest.raises(Exception):
    <do something bad here>

2022-05-18 14:32 UTC, swedchef commented on app/helpers/parse_dd20.py
> +        (?P<id>\\w)? makes a group 'id' and if there is a word in the end of the name it stores it
The regex description is somewhat incomplete. It is hard to give a short meaningful description of a regex, and i think it is okay to require some knowledge from the reader/coder. The anchors and modifiers are not mentioned and the "fixed" part is not either. Therefore, i would argue that it should be removed.

2022-05-18 14:32 UTC, swedchef commented on app/helpers/parse_dd20.py
> +        REGEX = r"^(?P<STN1>\w{3,4})-(?P<STN2>\w{3,4})-?(?P<id>\w)?$"
```suggestion
        REGEX = r"^(?P<STN1>\w{3,4})-(?P<STN2>\w{3,4})(-(?P<id>\w))?$"
```
I would argue this is more "correct". "Yours" will accept ABC-DEF34 - "mine" will require the second hyphen.

Be aware that \w will accept numbers as well - is this good, or bad?
we COULD replace "\w" with "[A-Za-zØÆÅøæå]" if we want to make sure it will only be standard alphabetical chars (including Danish custom chars).

```suggestion
        REGEX = r"^(?P<STN1>\w{3,4})-(?P<STN2>\w{3,4})(-(?P<id>\d))?$"
```

If the last group (id) should only accept numerical values, you can use \d in stead.

2022-05-30 07:41 UTC, stigsberg requested changes
Looks okay, there is a few issues in the documentation.
And I might have been the reason for one, sorry.

2022-05-30 07:41 UTC, stigsberg commented on README.md
> +When name git sconversion is not sufficient, due to discrepancies in naming, the "DD20 name to SCADA AC-line name mapping" is used to manually link AC-lines.
```suggestion
When standard name conversion is not sufficient, due to discrepancies in naming, the "DD20 name to SCADA AC-line name mapping" is used to manually link AC-lines.
```

2022-05-30 07:41 UTC, stigsberg commented on README.md
>  ## Help
I do not know if my suggestion had an error in its syntax for the md format. But at least it is now broken so that the entire last section is listed as a bash command.
I apologize if I am the reason for this. :)

2022-05-30 07:43 UTC, stigsberg commented on README.md
> +|DD20FILEPATH|/input/DD20.XLSM|Filepath for "DD20" excel-file|
What is the reason you use "_" to seperat some of the words.
I find it wierd that you use two different types of naming conventions.

2022-05-30 07:46 UTC, stigsberg commented on README.md
> +The container has an option to generate mock-data. This is done by taking the test-data files and dumping them into the input directory. This can be used if real forecast files are not available. Be
I will allow to reopen this again, since the error with hinting to a forecast type of file still exists in the documentation. But I will not call DD20 files a form of forecast. I do believe this is a copy paste error from the forecast parser.
Let me know if you still think I am wrong.

2022-05-30 12:38 UTC, swedchef requested changes
I'm a bit confused to be honest. Some of the comments i made have been marked as resolved, even though they have not been included or the main issue corrected, raised as an issue or had a comment attached to why they were closed. So i reopened some - and fear others might have been lost.

2022-05-30 12:38 UTC, swedchef commented on app/helpers/parse_dd20.py
> +            https://www.dataquest.io/blog/settingwithcopywarning/
Could you move this to an issue and then close it when you are done?

2022-05-30 12:38 UTC, swedchef commented on app/helpers/parse_dd20.py
> +        (?P<id>\\w)? makes a group 'id' and if there is a word in the end of the name it stores it
What should we do with this one? I suggest just removing it from the docstring, but i will not block in case you disagree.

2022-05-30 12:38 UTC, swedchef commented on app/main.py
> +                raise e
I get it - you are still adding issues, so when it's been added, please resolve this conversation as well - i just want to be certain it is added. You can reference the issue when you resolve the conversation for added traceability!

2022-05-30 12:38 UTC, swedchef commented on app/main.py
> +                )
So - this is somewhat different than last conversation. One for "could not read file" and one for "no file present" - guess that should be two issues, that perhaps could be solved with a single commit.

2022-05-30 12:38 UTC, swedchef commented on chart/Chart.yaml
>  description: A freshly created template-script
This is not resolved

2022-05-30 12:38 UTC, swedchef commented on README.md
> +When name git sconversion is not sufficient, due to discrepancies in naming, the "DD20 name to SCADA AC-line name mapping" is used to manually link AC-lines.
What about this one?

2022-05-30 12:38 UTC, swedchef commented on README.md
> +The container will now be running interactively and you will be able to see the log output. The container will need the input files availiable in the volume, since else it will crash.
"since else it will crash" is not good English.

2022-05-30 12:38 UTC, swedchef commented on README.md
> +Please submit an issue or ask the authors.
Why not include rest of the default-text?

2022-05-31 07:05 UTC, CodeWitten commented on README.md
> +When name git sconversion is not sufficient, due to discrepancies in naming, the "DD20 name to SCADA AC-line name mapping" is used to manually link AC-lines.
a mistype of git s(tatus)  has ended up here. removed it.

2022-05-31 11:54 UTC, CodeWitten commented on app/main.py
> +                raise e
issue added: https://github.com/energinet-singularity/conductor-data-provider/issues/15

2022-05-31 11:54 UTC, CodeWitten commented on app/main.py
> +                )
issue created https://github.com/energinet-singularity/conductor-data-provider/issues/16. 
I have created a task which focus on solving the two issues.

2022-05-31 11:54 UTC, CodeWitten commented on app/helpers/parse_dd20.py
> +            https://www.dataquest.io/blog/settingwithcopywarning/
Issue added and comment removed. https://github.com/energinet-singularity/conductor-data-provider/issues/17

2022-05-31 11:54 UTC, CodeWitten commented on app/helpers/parse_dd20.py
> +            Name of column containing allowed 40 hour ampere loading of cabling along the AC-line, if any.
i understand now. Changed in all modules such that it is equal and done the best way.

2022-05-31 11:54 UTC, CodeWitten commented on app/helpers/parse_dd20.py
> +        (?P<id>\\w)? makes a group 'id' and if there is a word in the end of the name it stores it
My suggestion is to leave the comment as is since it provides some information at least, and deal with making the regex properly as adressed in this issue. In the issue i also mentioned the docstring should be fixed with reference to your comment:
https://github.com/energinet-singularity/conductor-data-provider/issues/14

If you disagree let me know and i will delete the comment. I have close to no knowledege about regex.

2022-05-31 13:44 UTC, stigsberg approved these changes
Looks okay, then we will look into the issues created. :)

2022-06-01 06:55 UTC, swedchef approved these changes
All good. Just a single comment from me:

I argued you should use "load" instead of "loading" in your docstrings and suggested it. You did not take the change, but in the argumentation for still using "loading", you argued that "load" is the correct term, so it would seem we agree on the correct term, but you are still keeping the incorrect term. Not sure if i misunderstood something, or what happened. Leave it for now :)

Great work!

2022-06-01 11:03 UTC, swedchef approved these changes
You are a great Jedi!

2022-06-01 11:06 UTC, merged